### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign davidor markusthoemmes
/cc davidor markusthoemmes

### CODE REVIEW

**Comment by davidor** [comment]
We'll need to wait until the 0.16 release to merge this.

**Comment by dprotaso** [comment]
this is pulling the latest serving/master

/lgtm
/hold cancel

**Pull request merged**
