### PR TITLE
Remove logrus dependency and use common logger.

### PR DESCRIPTION
**Pull request by markusthoemmes**
This dependency seemed arbitrary and completely unneeded. So why not remove some code? :)

### CODE REVIEW

**Comment by jmprusi** [comment]
@markusthoemmes thanks! that's some leftover code we had there.. also the unit tests fails due to go-cmp (if you use the 4.0 this is fixed).

Let me try to get a PR merged that fixes this, and then you can rebase.

**Comment by markusthoemmes** [comment]
Rebased!

**Pull request merged**
