### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign davidor markusthoemmes
/cc davidor markusthoemmes

### CODE REVIEW

**Comment by davidor** [comment]
/hold

Conflicts with https://github.com/knative/net-kourier/pull/78

**Comment by jmprusi** [comment]
@davidor @markusthoemmes can this be "unhold"?

**Comment by davidor** [comment]
yes :+1:

**Pull request merged**
